### ISSUE TITLE
Can't enalbe any topic

### ISSUE THREAD

**Issue by kopach** [cerebroapp/cerebro-devdocs#3]
Can't enable any topic. Please, see demo below

![2021-10-16 21 34 18](https://user-images.githubusercontent.com/8749624/137600042-3db1772f-a3a1-4593-b31b-14ec55ecb85a.gif)

What am I doing wrong? How can I make it working? Please, advice

**Comment by MustCodeAl** [comment]
I can't enable any topic either

**Comment by josuetex** [comment]
I I have the same problem

**Comment by ayugioh2003** [comment]
same issue +1

**Comment by ptournet** [comment]
Same problem on Windows 10 with a brand new installation of both Cerebro and the plugin.
For the other people who have encountered that : please provide information on your setup, a bug is less likely to be resolved if there isn't sufficient information to reproduce it... ;)
